---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
  labels:
    app: search-engine
    component: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
      component: crawler
  template:
    metadata:
      name: crawler
      labels:
        app: search-engine
        component: crawler
    spec:
      containers:
      - image: yunusovtr/crawler:main
        name: crawler
        imagePullPolicy: Always
        env:
        - name: MONGO
          value: mongodb
        - name: MONGO_PORT
          value: "27017"
        - name: RMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_ERLANG_COOKIE
          value: "mycookie"
        - name: RMQ_USERNAME
          value: "rabbitmq"
        - name: RMQ_PASSWORD
          value: "rabbitmq"
        - name: RMQ_QUEUE
          value: "search-engine"
        - name: CHECK_INTERVAL
          value: "120"
        - name: EXCLUDE_URLS
          value: ".*github.com"
        - name: START_URL
          value: "https://vitkhab.github.io/search_engine_test_site/"
