---
image: alpine:latest

stages:
  - test
  - build
  - deploy

variables:
  DIND: docker:18.09.7-dind
  CI_REGISTRY: 'index.docker.io'
  CI_APPLICATION_TAG: $CI_COMMIT_REF_SLUG
  DOCKER_HOST: tcp://localhost:2375/
before_script:
  - CI_APPLICATION_REPOSITORY=$(echo "$CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME" | tr '[:upper:]' '[:lower:]')


test:
  stage: test
  image: python:3.6-alpine
  script:
    - pip install -r requirements.txt -r requirements-test.txt
    - python -m unittest discover -s tests/
    - coverage run -m unittest discover -s tests/
    - coverage xml --include crawler/crawler.py
  artifacts:
    reports:
      coverage_report: 
        coverage_format: cobertura
        path: coverage.xml
  only:
    - branches

build:
  stage: build
  only:
    - branches
  image: docker:git
  services:
    - $DIND
  script:
    - docker build -t "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG" .
    - echo "Logging to GitLab Container Registry with CI credentials...for build"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - echo "Pushing to GitLab Container Registry..."
    - docker push "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"

deploy:
  stage: deploy
  trigger:
    project: devops-project/Deploy
  only:
    - main
