apiVersion: monitoring.coreos.com/v1
kind: AlertmanagerConfig
metadata:
  name: config-example
  labels:
    alertmanagerConfig: example
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 1m
    repeatInterval: 5m
    receiver: 'email'
  receivers:
  - name: 'email'
    emailConfigs:
    - authIdentity: noreply@uc-osnovanie.ru
      authPassword:
        key: password
        name: email-config
      authUsername: noreply@uc-osnovanie.ru
      from: noreply@uc-osnovanie.ru
      to: 'timur.yunusov@uc-osnovanie.ru'
      requireTLS: false
      sendResolved: true
      smarthost: smtp.yandex.ru:465

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: email-config
data:
  password: {{ .Values.emailPassword }}
