---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "basic-ingress.fullname" . }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules: 
    - host: {{ .Values.ingress.host | default .Release.Name }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes
                port:
                  number: 443
