stages:
  - deploy

deploy:
  stage: deploy
  image: alpine/k8s:1.23.7
  variables:
    MONITORING_NS: monitoring
  only:
    - triggers
    - branches
  script:
    - kubectl version --client
    - kubectl config get-contexts
    - kubectl config use-context $(kubectl config get-contexts | tail -n +2 | head -n 1 | awk '{print $1};')
    - helm ls
    - kubectl describe ns $MONITORING_NS || kubectl create ns $MONITORING_NS
    - helm upgrade --install observation ./monitoring-stack -n $MONITORING_NS
    #--values prometheus-operator/values.yaml
    - echo "Grafana credentials:"
    - kubectl get secret/observation-grafana -n $MONITORING_NS -o json
    # - helm upgrade --install promtail grafana/promtail -f promtail/values.yaml -n $MONITORING_NS
    # - helm upgrade --install loki grafana/loki-distributed -n $MONITORING_NS
