galaxy_info:
  author: Ken Trenkelbach
  description: Create a NAT gateway from a Debian-based machine with UFW
  company: SSCC

  license: license MIT

  min_ansible_version: 1.2

  platforms:
  - name: Debian
    versions:
    - all
