---
port: 8000

image:
  repository:
  tag: main

mongo:
  host: mongodb
  port: 27017

checkInterval: 120
excludeUrls: ".*github.com"
startUrl: "https://vitkhab.github.io/search_engine_test_site/"
imagePullPolicy: Always
domain:
