{
 "title": "Search Engine Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Показатели",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Открытые страницы",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "web_pages_served", "legendFormat": "Count" }
     ]
    },
    {
     "title": "Страниц проиндексировано",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "crawler_pages_parsed", "legendFormat": "Count" }
     ]
    }
   ]
  },
  {
   "title": "Графики",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "web_page_gen_time_bucket",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
     "targets": [
      { "expr": "web_page_gen_time_bucket", "legendFormat": "{{ le }}" }
     ]
    },
    {
     "title": "crawler_site_connection_time_bucket",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "crawler_site_connection_time_bucket",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "crawler_page_parse_time_bucket",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "targets": [
      { "expr": "crawler_page_parse_time_bucket", "legendFormat": "{{ le }}" }
     ]
    }
   ]
  },
  {
   "title": "Логи",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Логи UI",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "{app=\"search-engine\", component=\"ui\"} |= ``"
      }
     ]
    },
    {
     "title": "Логи Crawler",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "{app=\"search-engine\", component=\"crawler\"} |= ``"
      }
     ]
    }
   ]
  }
 ]
}