---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: search-engine
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        env:
        - name: MONGO
          value: "{{ .Values.mongo.host | default ( printf "%s-%s" .Release.Name "mongodb" ) }}"
        - name: MONGO_PORT
          value: "{{ .Values.mongo.port }}"
        - name: RMQ_HOST
          value: "{{ .Values.rmq.host | default ( printf "%s-%s" .Release.Name "rabbitmq" ) }}"
        - name: RABBITMQ_ERLANG_COOKIE
          value: "mycookie"
        - name: RMQ_USERNAME
          value: "{{ .Values.rmq.username }}"
        - name: RMQ_PASSWORD
          value: "{{ .Values.rmq.password }}"
        - name: RMQ_QUEUE
          value: "{{ .Values.rmq.queue }}"
        - name: CHECK_INTERVAL
          value: "{{ .Values.checkInterval }}"
        - name: EXCLUDE_URLS
          value: "{{ .Values.excludeUrls }}"
        - name: START_URL
          value: "{{ .Values.startUrl }}"
